/**
 * This file is auto-generated by Thrift2Ts.
 *
 * Wed Jul 05 2017 18:13:15 GMT+0800 (CST)
 */

import { CalculatorClient } from "./tutorialClient"


export default {
    Calculator: CalculatorClient
}
